@extends('layouts.app')
@section('content')
    <h1>@lang('titles.meditation')</h1>
    <p>@lang('content.meditation')</p>
    <h1>@lang('titles.coaching')</h1>
    <p>@lang('content.coaching')</p>
    <h1>@lang('titles.spirituality')</h1>
    <p>@lang('content.spirituality')</p>
@endsection